<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * PortsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PortsRepository extends \Doctrine\ORM\EntityRepository
{
}
