<?php

namespace Ecommerce\EcommerceBundle\Repository;

/**
 * ProduitsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends \Doctrine\ORM\EntityRepository
{
    public function byCategorie($categorie)
    {
        $qb = $this->createQueryBuilder('u')
                ->select('u')
                ->where('u.categorie = :categorie')
                ->orderBy('u.id')
                ->setParameter('categorie', $categorie);

        return $qb->getQuery()->getResult();
    }

    public function recherche($nom)
    {
        $qb = $this->createQueryBuilder('p')
              ;

        $qb
     ->where('p.nom like :nom')
     ->andWhere('p.disponible = 1')
     ->setParameter('nom', $nom)
      ;

        return $qb
        ->getQuery()
        ->getResult()
      ;
    }

    public function findArray($tab)
    {
        $qb = $this->createQueryBuilder('p')
              ;
        $qb
     ->where('p.id IN (:tab)')
     ->setParameter('tab', $tab)
      ;

        return $qb
        ->getQuery()
        ->getResult()
      ;
    }
}
