factures:
    path: /profile/factures
    defaults: { _controller: UtilisateursBundle:Utilisateurs:factures }
    
facturesPDF:
    path: /profile/factures/pdf/{id}
    defaults: { _controller: UtilisateursBundle:Utilisateurs:facturesPDF }

